set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -s set-clipboard on
set -g mouse on

set-window-option -g visual-bell on
set-window-option -g bell-action other

set-option -g prefix C-space

set -g detach-on-destroy no-detached
set -g base-index 1
set -g renumber-windows on

# Set the escape time to 100 for the first second of a session
# This allows tmux to communicate freely with the terminal emulator, but
# but prevents a noticeable input lag.
set -s escape-time 100
set-hook -g client-attached 'run-shell -b "sleep 1; tmux set -s escape-time 0"'
set-hook -g client-detached 'set -s escape-time 100'

%if #{==:#{TMUX_ACCENT},}
    TMUX_ACCENT=red
%endif

run-shell -b '~/.config/tmux/update-path.sh "#{session_path}" "#{session_name}"'
set-hook -g client-session-changed 'run-shell -b \
    "~/.config/tmux/update-path.sh \"#{session_path}\" \"#{session_name}\""'
set-hook -g client-resized 'run-shell -b \
    "~/.config/tmux/update-path.sh \"#{session_path}\" \"#{session_name}\""'

set -g status-style ""
set -g status-position top
set -g status-justify absolute-centre
set -g status-left "#{session_display_path}"
set -g status-left-length 50
set -g status-right \
"#[bg=default,fg=default]#{USER}@#{host}\
#{?client_prefix, "#[fg=$TMUX_ACCENT]", "#[fg=default]"}  "

set -g pane-border-status "top"
set -g pane-border-lines "single"
set -g pane-border-style "fg=black"
set -g pane-active-border-style "fg=black"
set -g pane-border-format ""

set -g window-style "fg=white"
set -g window-active-style "fg=brightwhite"

# Highlight the active pane only if there is more than one pane
set -g window-status-style "fg=white"
set -g window-status-current-style "fg=$TMUX_ACCENT,bold"
set -g window-status-format "#I.#W"
set -g window-status-current-format "#I.#{window_name}"

set -g message-style "fg=white bg=black"
set -g prompt-cursor-style "bar"
set -g prompt-cursor-color "white"

set -g menu-style ""
set -g menu-selected-style "bg=$TMUX_ACCENT fg=black"

set -g clock-mode-colour "$TMUX_ACCENT"

set -g mode-style "bg=$TMUX_ACCENT fg=black"
set -g copy-mode-selection-style "bg=brightblack fg=brightwhite"
set -g cursor-style "block"
set -g cursor-color "white"

bind -N "Reload config" r source-file ~/.config/tmux/tmux.conf

# Pane switching
bind -N "Switch to the window above" -r k select-pane -U
bind -N "Switch to the window below" -r j select-pane -D
bind -N "Switch to the window to the left" -r h select-pane -L
bind -N "Switch to the window to the right" -r l select-pane -R

bind -N "Split the window vertically" v split-window -h
bind -N "Split the window horizontally" n split-window -v # Collides with next-window

bind -N "Next window" -r -n C-Tab next-window
bind -N "Previous window" -r -n C-S-Left previous-window

bind -N "Launch project picker" \
    o run "tmux neww ~/.config/scripts/tmux-sessions.sh select project" 

bind -N "Launch project picker (with hidden files)" \
    O run "tmux neww ~/.config/scripts/tmux-sessions.sh select-all project" 

bind -N "Launch directory picker" \
    f run "tmux neww ~/.config/scripts/tmux-sessions.sh select directory" 

bind -N "Launch directory picker (with hidden files)" \
    F run "tmux neww ~/.config/scripts/tmux-sessions.sh select-all directory" 

bind -N "Open dotfiles" \
    D run "~/.config/scripts/tmux-sessions.sh open ~/dotfiles"
