set-option -g prefix C-a

set -g base-index 1
set -g renumber-windows on
set -g mode-keys vi

set -g status-left "[#{session_index}/#{session_count}] #S"
set -g status-right "#{session_path}"

set -g status-position top
set -g status-justify absolute-centre
set -g status-style ""

set -g pane-border-lines "spaces"
set -g pane-border-indicators "arrows"
set -g pane-border-status "top"
set -g pane-border-style "fg=brightblack"
set -g pane-active-border-style "fg=gray"

set -g window-status-style "fg=white"
set -g window-status-current-style "fg=green,bold"
set -g window-status-format "#I.#W"
set -g window-status-current-format "#I.#{window_name}"

set -g message-style "fg=white"
set -g prompt-cursor-style "blinking-bar"
set -g prompt-cursor-color "white"

set -g menu-style ""
set -g menu-selected-style "fg=green"

set -g cursor-style "blinking-bar"
set -g cursor-color "white"

bind -N "Reload config" r source-file ~/.config/tmux/tmux.conf

# Pane switching
bind -N "Switch to the window above" -r k select-pane -U
bind -N "Switch to the window below" -r j select-pane -D
bind -N "Switch to the window to the left" -r h select-pane -L
bind -N "Switch to the window to the right" -r l select-pane -R

bind -N "Split the window vertically" v split-window -h
bind -N "Split the window horizontally" n split-window -v # Collides with next-window

bind -N "Next window" -r -n C-Tab next-window
bind -N "Previous window" -r -n C-S-Left previous-window

# Copy mode
# setw -g mode-keys vi
# bind-key -T copy-mode-vi 'v' send -X begin-selection     # Begin selection in copy mode.
# bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle  # Begin selection in copy mode.
# bind-key -T copy-mode-vi 'y' send -X copy-selection      # Yank selection in copy mode.
# unbind-key -T copy-mode-vi v

# bind-key -T copy-mode-vi v send-keys -X begin-slection


