set-option -g prefix C-a

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

# Set the escape time to 100 for the first second of a session
# This allows tmux to communicate freely with the terminal emulator, but
# but prevents a noticeable input lag.
set -s escape-time 100
set-hook -g client-attached 'run-shell -b "sleep 1; tmux set -s escape-time 0"'
set-hook -g client-detached 'set -s escape-time 100'

set -g base-index 1
set -g renumber-windows on
set -g mode-keys vi

set -g status-left "#S"
set -g status-left-length 20
set -g status-right "#{user}@#{host}"

set -g status-position top
set -g status-justify absolute-centre
set -g status-style ""

# Highlight the active pane only if there is more than one pane
set -g pane-border-indicators "off"
set -g pane-active-border-style "fg=black"
set-hook -g window-layout-changed 'if-shell -F "#{==:#{window_panes},1}" \
  "set -w pane-active-border-style \"fg=black\"" \
  "set -w pane-active-border-style \"fg=brightblack\""'

# set -g pane-border-lines "spaces"
set -g pane-border-status "top"
set -g pane-border-style "fg=black"
set -g pane-border-format ""

set -g window-status-style "fg=white"
set -g window-status-current-style "fg=green,bold"
set -g window-status-format "#I.#W"
set -g window-status-current-format "#I.#{window_name}"

set -g message-style "fg=white"
# set -g prompt-cursor-style "blinking-bar"
# set -g prompt-cursor-color "white"

set -g menu-style ""
set -g menu-selected-style "fg=green"

set -g mode-style "fg=blue"

set -g cursor-style "blinking-bar"
set -g cursor-color "white"

bind -N "Reload config" r source-file ~/.config/tmux/tmux.conf

# Pane switching
bind -N "Switch to the window above" -r k select-pane -U
bind -N "Switch to the window below" -r j select-pane -D
bind -N "Switch to the window to the left" -r h select-pane -L
bind -N "Switch to the window to the right" -r l select-pane -R

bind -N "Split the window vertically" v split-window -h
bind -N "Split the window horizontally" n split-window -v # Collides with next-window

bind -N "Next window" -r -n C-Tab next-window
bind -N "Previous window" -r -n C-S-Left previous-window

bind -N "Session directory picker" \
    f run "tmux neww ~/.config/scripts/tmux-sessions.sh" 
    
bind -N "Dotfiles" \
    D run "~/.config/scripts/tmux-sessions.sh ~/dotfiles"
