set $background "#121212"
set $dim_background "#000000"
set $foreground "#cccccc"
set $dim_foreground "#999999"

set $black "#232323"
set $red "#d44d4f"
set $green "#67a376"
set $yellow "#f4c451"
set $blue "#78a7f0"
set $purple "#b575e9"
set $cyan "#4eccf2"
set $white "#b3b3b3"

set $bright_black "#5e5d5d"
set $bright_red "#ed7375"
set $bright_green "#9ae3ac"
set $bright_yellow "#f9f1a5"
set $bright_blue "#8bc4f0"
set $bright_purple "#c59be7"
set $bright_cyan "#9fd3ed"
set $bright_white "#d6d6d6"

set $dim_black "#090909"
set $dim_red "#4b2526"
set $dim_green "#233726"
set $dim_yellow "#1f1e1c"
set $dim_blue "#28364d"

set $primary $green
set $bright_primary $bright_green
set $dim_primary $dim_green
set $secondary $blue
set $bright_secondary $bright_blue
set $accent $purple
set $bright_accent $bright_purple


client.focused $white $background $foreground $bright_black $white
client.focused_inactive $white $dim_background $dim_foreground $bright_black $bright_black
client.unfocused $white $dim_background $dim_foreground $bright_black $bright_black

