hl.config({ autogenerated = false })

require("modules.monitors")
require("modules.options")
require("modules.input")
require("modules.animations")
require("modules.keybinds")

require("modules.window_rules")
require("modules.quick_access")
require("modules.auto_float")
require("modules.style_maximized")

-- DMS Include Configs
require("dms.outputs")
