hl.config({ autogenerated = false })

require("hyprland.monitors")
require("hyprland.appearance")
require("hyprland.layouts")
require("hyprland.animations")
require("hyprland.misc")
require("hyprland.keybinds")
require("hyprland.window_rules")
