hl.config({ autogenerated = false })

require("modules.monitors")
require("modules.behaviour")
require("modules.input")
require("modules.appearance")
require("modules.layouts")
require("modules.animations")
require("modules.keybinds")
require("modules.auto_start")

require("modules.window_rules")
require("modules.quick_access")
require("modules.auto_float")
require("modules.style_maximized")

