# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usbhid" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/lvm-root";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/mapper/luks-46377bbb-2b94-4c98-b751-ea44c5ee2ecb";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-46377bbb-2b94-4c98-b751-ea44c5ee2ecb".device = "/dev/mapper/lvm-home";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/90AD-1807";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/lvm-swap"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
