[general]
import = [ "colors.toml" ]

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 120, lines = 35 }
decorations = "Transparent"
dynamic_title = true
padding = { x = 15, y = 15 }
opacity = 1 

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "Off" }

[font]
normal = { family = "JetBrains Mono", style = "SemiBold" }
bold = { family = "JetBrains Mono", style = "ExtraBold" }
size = 12
offset = { x = 0, y = 0 }

[keyboard]
bindings = [
    # Send Control+Tab code
    { mods = "Control", key = "Tab", chars = "\u001b[27;5;9~"},
    # Map Control+Shift+Tab to Control+Shift+Left
    { mods = "Control|Shift", key = "Tab", chars = "\u001b[1;6D"},

    { mods = "Control|Shift", key = "Return", action = "SpawnNewInstance"}
]


