[terminal]
shell = { program = "wsl -- tmux" }

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 120, lines = 35 }
decorations = "Transparent"
dynamic_title = true
padding = { x = 10, y = 10 }
opacity = 1 

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "Off" }

[colors]
cursor = { text = "#121212", cursor = "#cccccc" }

[colors.primary]
background = "#121212"
foreground = "#cccccc"

[colors.normal]
black = "#202020"
red = "#d44d4f"
green = "#67a376"
yellow = "#f4c451"
blue = "#78a7f0"
magenta = "#b575e9"
cyan = "#4eccf2"
white = "#b3b3b3"

[colors.bright]
black = "#5e5d5d"
red = "#ed7375"
green = "#9ae3ac"
yellow = "#f9f1a5"
blue = "#8bc4f0"
magenta = "#c59be7"
cyan = "#9fd3ed"
white = "#d6d6d6"

[font]
normal = { family = "JetBrainsMono NF", style = "SemiBold" }
size = 10
offset = { x = 1, y = 0 }

[keyboard]
bindings = [
    # Send Control+Tab code
    { mods = "Control", key = "Tab", chars = "\u001b[27;5;9~"},
    # Map Control+Shift+Tab to Control+Shift+Left
    { mods = "Control|Shift", key = "Tab", chars = "\u001b[1;6D"},

    # Navigate throught the prompt with Alt+hjkl and Alt+HJKL
    { mods = "Alt", key = "h", chars = "\u001b[D"},
    { mods = "Alt", key = "l", chars = "\u001b[C"},
    { mods = "Alt|Shift", key = "h", chars = "\u001b[1;5D"},
    { mods = "Alt|Shift", key = "l", chars = "\u001b[1;5C"},
    { mods = "Alt", key = "j", chars = "\u001b[B" },
    { mods = "Alt", key = "k", chars = "\u001b[A" }
]


